import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

f = pd.read_csv('figs/stats.csv', mangle_dupe_cols=True)
#dropout_nll = np.asarray(f['Dropout+AC0-NLL']).reshape((-1,1))
#dropout_mse = np.asarray(f['Dropout+AC0-MSE']).reshape((-1,1))
#ensemble_nll = np.asarray(f['Ensemble+AC0-NLL']).reshape((-1,1))
#ensemble_mse = np.asarray(f['Ensemble+AC0-MSE']).reshape((-1,1))
#sigma_nll = np.asarray(f['Sigma+AC0-NLL']).reshape((-1,1))
#sigma_mse = np.asarray(f['Sigma+AC0-MSE']).reshape((-1,1))
#hydranet_nll = np.asarray(f['HydraNet+AC0-NLL']).reshape((-1,1))
#hydranet_mse = np.asarray(f['HydraNet+AC0-MSE']).reshape((-1,1))
#hydra_sigma_nll = np.asarray(f['HydraNet+AC0-Sigma+AC0-NLL']).reshape((-1,1))
#hydra_sigma_mse = np.asarray(f['HydraNet+AC0-Sigma+AC0-MSE']).reshape((-1,1))
dropout_nll = np.asarray(f['Dropout-NLL']).reshape((-1,1))
dropout_mse = np.asarray(f['Dropout-MSE']).reshape((-1,1))
ensemble_nll = np.asarray(f['Ensemble-NLL']).reshape((-1,1))
ensemble_mse = np.asarray(f['Ensemble-MSE']).reshape((-1,1))
sigma_nll = np.asarray(f['Sigma-NLL']).reshape((-1,1))
sigma_mse = np.asarray(f['Sigma-MSE']).reshape((-1,1))
hydranet_nll = np.asarray(f['HydraNet-NLL']).reshape((-1,1))
hydranet_mse = np.asarray(f['HydraNet-MSE']).reshape((-1,1))
hydra_sigma_nll = np.asarray(f['HydraNet-Sigma-NLL']).reshape((-1,1))
hydra_sigma_mse = np.asarray(f['HydraNet-Sigma-MSE']).reshape((-1,1))

nll_losses = np.hstack((dropout_nll, ensemble_nll, sigma_nll, hydranet_nll, hydra_sigma_nll))
plt.figure()
plt.clf()
plt.rc('text', usetex=True)
plt.rc('font', family='serif')
plt.boxplot(nll_losses)
#plt.ylim(0,100)
plt.title('NLL')
plt.grid()
plt.xticks([1, 2, 3, 4, 5], ['Dropout', 'Ensemble', 'Sigma', 'HydraNet', 'HydraNet-Sigma'])
plt.xticks(rotation=20)
plt.yscale('log')
plt.savefig('figs/uncertainty-NLL.pdf', format='pdf', dpi=800, bbox_inches='tight')

mse_losses = np.hstack((dropout_mse, ensemble_mse, sigma_mse, hydranet_mse, hydra_sigma_mse))
plt.figure()
plt.clf()
plt.rc('text', usetex=True)
plt.rc('font', family='serif')
plt.boxplot(mse_losses)
#plt.ylim(0,100)
plt.title('MSE')
plt.grid()
plt.xticks([1, 2, 3, 4, 5], ['Dropout', 'Ensemble', 'Sigma', 'HydraNet', 'HydraNet-Sigma'])
plt.xticks(rotation=20)
plt.yscale('log')
plt.savefig('figs/uncertainty-MSE.pdf', format='pdf', dpi=800, bbox_inches='tight')